name: Unpack ZIP to root
on:
  push:
    paths:
      - 'site.zip'
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Clean old site (keep workflow & zip)
        run: |
          shopt -s extglob
          rm -rf !(site.zip|.github)
      - name: Unzip site.zip
        run: |
          unzip -q site.zip
          TOP=$(zipinfo -1 site.zip | head -1 | cut -d/ -f1)
          if [ -d "$TOP" ]; then
            shopt -s dotglob
            mv "$TOP"/* .
            rmdir "$TOP" || true
          fi
      - name: Ensure .nojekyll
        run: touch .nojekyll
      - name: Commit unpacked site
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unpack site.zip to root" || echo "Nothing to commit"
          git push
